import { defineConfig } from "tsdown";

export default defineConfig({
	clean: true,
	dts: true,
	entry: [
		"./lib/index.ts",
		"./lib/asset-cleanup-service.ts",
		"./lib/placeholder-values.ts",
		"./lib/placeholder-values-service.ts",
		"./lib/client.ts",
		"./lib/content-block-cleanup-service.ts",
		"./lib/social-media-cleanup-service.ts",
		"./lib/errors.ts",
		"./lib/image-captions.ts",
		"./lib/integrity-service.ts",
		"./lib/link-targets.ts",
		"./lib/link-targets-service.ts",
		"./lib/relations.ts",
		"./lib/rich-text.ts",
		"./lib/rich-text-normalize.ts",
		"./lib/richtext-cleanup-service.ts",
		"./lib/richtext-link-cleanup-service.ts",
		"./lib/schema.ts",
		"./lib/sql.ts",
	],
	format: ["esm"],
	minify: false,
	sourcemap: true,
	treeshake: true,
});
