/* eslint-disable no-restricted-syntax */

import { define } from "@acdh-knowledge-base/env";
import * as v from "valibot";

const validate = define({
	envVars: v.object({
		CAMPUS_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		DATABASE_HOST: v.pipe(v.string(), v.nonEmpty()),
		DATABASE_NAME: v.pipe(v.string(), v.nonEmpty()),
		DATABASE_PASSWORD: v.pipe(v.string(), v.minLength(8)),
		DATABASE_PORT: v.pipe(v.string(), v.toNumber(), v.integer(), v.minValue(1)),
		DATABASE_SSL_CONNECTION: v.optional(v.picklist(["disabled", "enabled"]), "disabled"),
		DATABASE_USER: v.pipe(v.string(), v.nonEmpty()),
		EPISCIENCES_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		HAL_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		OPENAIRE_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		S3_ACCESS_KEY: v.pipe(v.string(), v.nonEmpty()),
		S3_BUCKET_NAME: v.pipe(v.string(), v.nonEmpty()),
		S3_HOST: v.pipe(v.string(), v.nonEmpty()),
		S3_PORT: v.pipe(v.string(), v.toNumber(), v.integer(), v.minValue(1)),
		S3_PROTOCOL: v.optional(v.picklist(["http", "https"]), "http"),
		S3_SECRET_KEY: v.pipe(v.string(), v.nonEmpty()),
		SSHOC_MARKETPLACE_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		SSHOC_MARKETPLACE_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		SSHOC_MARKETPLACE_PASSWORD: v.optional(v.pipe(v.string(), v.nonEmpty())),
		SSHOC_MARKETPLACE_USER: v.optional(v.pipe(v.string(), v.nonEmpty())),
		TYPESENSE_ADMIN_API_KEY: v.pipe(v.string(), v.nonEmpty()),
		TYPESENSE_RESOURCE_COLLECTION_NAME: v.pipe(v.string(), v.nonEmpty()),
		TYPESENSE_WEBSITE_COLLECTION_NAME: v.pipe(v.string(), v.nonEmpty()),
		TYPESENSE_HOST: v.pipe(v.string(), v.nonEmpty()),
		TYPESENSE_PORT: v.pipe(v.string(), v.toNumber(), v.integer(), v.minValue(1)),
		TYPESENSE_PROTOCOL: v.optional(v.picklist(["http", "https"]), "https"),
		ZENODO_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		ZOTERO_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		ZOTERO_API_KEY: v.optional(v.pipe(v.string(), v.nonEmpty())),
		ZOTERO_GROUP_ID: v.optional(v.pipe(v.string(), v.nonEmpty())),
	}),
});

export const env = validate({
	environment: {
		CAMPUS_API_BASE_URL: process.env.CAMPUS_API_BASE_URL,
		DATABASE_HOST: process.env.DATABASE_HOST,
		DATABASE_NAME: process.env.DATABASE_NAME,
		DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
		DATABASE_PORT: process.env.DATABASE_PORT,
		DATABASE_SSL_CONNECTION: process.env.DATABASE_SSL_CONNECTION,
		DATABASE_USER: process.env.DATABASE_USER,
		EPISCIENCES_API_BASE_URL: process.env.EPISCIENCES_API_BASE_URL,
		HAL_API_BASE_URL: process.env.HAL_API_BASE_URL,
		OPENAIRE_API_BASE_URL: process.env.OPENAIRE_API_BASE_URL,
		S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
		S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
		S3_HOST: process.env.S3_HOST,
		S3_PORT: process.env.S3_PORT,
		S3_PROTOCOL: process.env.S3_PROTOCOL,
		S3_SECRET_KEY: process.env.S3_SECRET_KEY,
		SSHOC_MARKETPLACE_API_BASE_URL: process.env.SSHOC_MARKETPLACE_API_BASE_URL,
		SSHOC_MARKETPLACE_BASE_URL: process.env.SSHOC_MARKETPLACE_BASE_URL,
		SSHOC_MARKETPLACE_PASSWORD: process.env.SSHOC_MARKETPLACE_PASSWORD,
		SSHOC_MARKETPLACE_USER: process.env.SSHOC_MARKETPLACE_USER,
		TYPESENSE_ADMIN_API_KEY: process.env.TYPESENSE_ADMIN_API_KEY,
		TYPESENSE_RESOURCE_COLLECTION_NAME: process.env.TYPESENSE_RESOURCE_COLLECTION_NAME,
		TYPESENSE_WEBSITE_COLLECTION_NAME: process.env.TYPESENSE_WEBSITE_COLLECTION_NAME,
		TYPESENSE_HOST: process.env.TYPESENSE_HOST,
		TYPESENSE_PORT: process.env.TYPESENSE_PORT,
		TYPESENSE_PROTOCOL: process.env.TYPESENSE_PROTOCOL,
		ZENODO_API_BASE_URL: process.env.ZENODO_API_BASE_URL,
		ZOTERO_API_BASE_URL: process.env.ZOTERO_API_BASE_URL,
		ZOTERO_API_KEY: process.env.ZOTERO_API_KEY,
		ZOTERO_GROUP_ID: process.env.ZOTERO_GROUP_ID,
	},
}).unwrap();
