services:
  postgres:
    image: postgres:18
    container_name: the-knowledge-base-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      # for psql
      PGDATABASE: ${DATABASE_NAME}
      PGPASSWORD: ${DATABASE_PASSWORD}
      PGUSER: ${DATABASE_USER}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}"']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
    name: the-knowledge-base-postgres-data

networks:
  default:
    name: the-knowledge-base
