import { addTrailingSlash, removeTrailingSlash } from "@acdh-oeaw/lib";
import { define } from "@acdh-knowledge-base/env";
import * as v from "valibot";

const validate = define({
	buildArgsPrefix: "NEXT_PUBLIC_",
	buildArgs: v.object({
		NEXT_PUBLIC_APP_BASE_URL: v.pipe(v.string(), v.url(), v.transform(removeTrailingSlash)),
		NEXT_PUBLIC_APP_BOTS: v.optional(v.picklist(["disabled", "enabled"]), "disabled"),
		NEXT_PUBLIC_APP_GOOGLE_SITE_VERIFICATION: v.optional(v.pipe(v.string(), v.nonEmpty())),
		NEXT_PUBLIC_APP_IMPRINT_CUSTOM_CONFIG: v.optional(
			v.picklist(["disabled", "enabled"]),
			"enabled",
		),
		NEXT_PUBLIC_APP_IMPRINT_SERVICE_BASE_URL: v.pipe(
			v.string(),
			v.url(),
			v.transform(removeTrailingSlash),
		),
		NEXT_PUBLIC_APP_MATOMO_BASE_URL: v.optional(
			v.pipe(v.string(), v.url(), v.transform(addTrailingSlash)),
		),
		NEXT_PUBLIC_APP_MATOMO_ID: v.optional(
			v.pipe(v.string(), v.toNumber(), v.integer(), v.minValue(1)),
		),
		NEXT_PUBLIC_APP_SENTRY_DSN: v.optional(v.pipe(v.string(), v.nonEmpty())),
		NEXT_PUBLIC_APP_SENTRY_ORG: v.optional(v.pipe(v.string(), v.nonEmpty())),
		NEXT_PUBLIC_APP_SENTRY_PII: v.optional(v.picklist(["disabled", "enabled"]), "disabled"),
		NEXT_PUBLIC_APP_SENTRY_PROJECT: v.optional(v.pipe(v.string(), v.nonEmpty())),
		NEXT_PUBLIC_APP_SERVICE_ID: v.pipe(v.string(), v.toNumber(), v.integer(), v.minValue(1)),
		NEXT_PUBLIC_TYPESENSE_RESOURCE_COLLECTION_NAME: v.pipe(v.string(), v.nonEmpty()),
		NEXT_PUBLIC_TYPESENSE_WEBSITE_COLLECTION_NAME: v.pipe(v.string(), v.nonEmpty()),
		NEXT_PUBLIC_TYPESENSE_HOST: v.pipe(v.string(), v.nonEmpty()),
		NEXT_PUBLIC_TYPESENSE_PORT: v.pipe(v.string(), v.toNumber(), v.integer(), v.minValue(1)),
		NEXT_PUBLIC_TYPESENSE_PROTOCOL: v.optional(v.picklist(["http", "https"]), "https"),
		/**
		 * Optional, because we need to be able to create a collection, before we create a search-only
		 * api key for that collection.
		 */
		NEXT_PUBLIC_TYPESENSE_SEARCH_API_KEY: v.optional(v.pipe(v.string(), v.nonEmpty())),
	}),
	envVars: v.object({
		APP_SENTRY_AUTH_TOKEN: v.optional(v.pipe(v.string(), v.nonEmpty())),
		AUTH_ENCRYPTION_KEY: v.pipe(v.string(), v.length(32)),
		AUTH_SIGN_UP: v.optional(v.picklist(["disabled", "enabled"]), "disabled"),
		BUILD_MODE: v.optional(v.picklist(["export", "standalone"])),
		CAMPUS_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		CI: v.optional(v.pipe(v.unknown(), v.toBoolean())),
		DATABASE_HOST: v.pipe(v.string(), v.nonEmpty()),
		DATABASE_NAME: v.pipe(v.string(), v.nonEmpty()),
		DATABASE_PASSWORD: v.pipe(v.string(), v.minLength(8)),
		DATABASE_PORT: v.pipe(v.string(), v.toNumber(), v.integer(), v.minValue(1)),
		DATABASE_SSL_CONNECTION: v.optional(v.picklist(["disabled", "enabled"]), "disabled"),
		DATABASE_USER: v.pipe(v.string(), v.nonEmpty()),
		EMAIL_ADDRESS: v.pipe(v.string(), v.email()),
		EMAIL_SMTP_PASSWORD: v.optional(v.pipe(v.string(), v.nonEmpty())),
		EMAIL_SMTP_PORT: v.pipe(v.string(), v.toNumber(), v.integer(), v.minValue(1)),
		EMAIL_SMTP_SERVER: v.pipe(v.string(), v.nonEmpty()),
		EMAIL_SMTP_USERNAME: v.optional(v.pipe(v.string(), v.nonEmpty())),
		EMAIL_SSL_CONNECTION: v.optional(v.picklist(["disabled", "enabled"]), "disabled"),
		EPISCIENCES_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		IMGPROXY_BASE_URL: v.pipe(v.string(), v.url()),
		IMGPROXY_KEY: v.pipe(v.string(), v.nonEmpty()),
		IMGPROXY_SALT: v.pipe(v.string(), v.nonEmpty()),
		MAILCHIMP_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		MAILCHIMP_API_KEY: v.optional(v.pipe(v.string(), v.nonEmpty())),
		MAILCHIMP_LIST_ID: v.optional(v.pipe(v.string(), v.nonEmpty())),
		MAILPIT_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		NEXT_RUNTIME: v.optional(v.picklist(["edge", "nodejs"])),
		REVALIDATION_WEBHOOK_SECRET: v.optional(v.pipe(v.string(), v.nonEmpty())),
		REVALIDATION_WEBHOOK_URL: v.optional(v.pipe(v.string(), v.url())),
		S3_ACCESS_KEY: v.pipe(v.string(), v.nonEmpty()),
		S3_BUCKET_NAME: v.pipe(v.string(), v.nonEmpty()),
		S3_HOST: v.pipe(v.string(), v.nonEmpty()),
		S3_PORT: v.pipe(v.string(), v.toNumber(), v.integer(), v.minValue(1)),
		S3_PROTOCOL: v.optional(v.picklist(["http", "https"]), "https"),
		S3_SECRET_KEY: v.pipe(v.string(), v.nonEmpty()),
		SEARCH_SYNC_API_SECRET: v.optional(v.pipe(v.string(), v.nonEmpty())),
		SSHOC_MARKETPLACE_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		SSHOC_MARKETPLACE_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		TYPESENSE_ADMIN_API_KEY: v.pipe(v.string(), v.nonEmpty()),
		ZOTERO_API_BASE_URL: v.optional(v.pipe(v.string(), v.url())),
		ZOTERO_API_KEY: v.optional(v.pipe(v.string(), v.nonEmpty())),
		ZOTERO_GROUP_ID: v.optional(v.pipe(v.string(), v.nonEmpty())),
	}),
});

export const env = validate({
	environment: {
		APP_SENTRY_AUTH_TOKEN: process.env.APP_SENTRY_AUTH_TOKEN,
		AUTH_ENCRYPTION_KEY: process.env.AUTH_ENCRYPTION_KEY,
		AUTH_SIGN_UP: process.env.AUTH_SIGN_UP,
		BUILD_MODE: process.env.BUILD_MODE,
		CAMPUS_API_BASE_URL: process.env.CAMPUS_API_BASE_URL,
		CI: process.env.CI,
		DATABASE_HOST: process.env.DATABASE_HOST,
		DATABASE_NAME: process.env.DATABASE_NAME,
		DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
		DATABASE_PORT: process.env.DATABASE_PORT,
		DATABASE_SSL_CONNECTION: process.env.DATABASE_SSL_CONNECTION,
		DATABASE_USER: process.env.DATABASE_USER,
		EMAIL_ADDRESS: process.env.EMAIL_ADDRESS,
		EMAIL_SMTP_PASSWORD: process.env.EMAIL_SMTP_PASSWORD,
		EMAIL_SMTP_PORT: process.env.EMAIL_SMTP_PORT,
		EMAIL_SMTP_SERVER: process.env.EMAIL_SMTP_SERVER,
		EMAIL_SMTP_USERNAME: process.env.EMAIL_SMTP_USERNAME,
		EMAIL_SSL_CONNECTION: process.env.EMAIL_SSL_CONNECTION,
		EPISCIENCES_API_BASE_URL: process.env.EPISCIENCES_API_BASE_URL,
		IMGPROXY_BASE_URL: process.env.IMGPROXY_BASE_URL,
		IMGPROXY_KEY: process.env.IMGPROXY_KEY,
		IMGPROXY_SALT: process.env.IMGPROXY_SALT,
		MAILCHIMP_API_BASE_URL: process.env.MAILCHIMP_API_BASE_URL,
		MAILCHIMP_API_KEY: process.env.MAILCHIMP_API_KEY,
		MAILCHIMP_LIST_ID: process.env.MAILCHIMP_LIST_ID,
		MAILPIT_API_BASE_URL: process.env.MAILPIT_API_BASE_URL,
		NEXT_PUBLIC_APP_BASE_URL: process.env.NEXT_PUBLIC_APP_BASE_URL,
		NEXT_PUBLIC_APP_BOTS: process.env.NEXT_PUBLIC_APP_BOTS,
		NEXT_PUBLIC_APP_GOOGLE_SITE_VERIFICATION: process.env.NEXT_PUBLIC_APP_GOOGLE_SITE_VERIFICATION,
		NEXT_PUBLIC_APP_IMPRINT_CUSTOM_CONFIG: process.env.NEXT_PUBLIC_APP_IMPRINT_CUSTOM_CONFIG,
		NEXT_PUBLIC_APP_IMPRINT_SERVICE_BASE_URL: process.env.NEXT_PUBLIC_APP_IMPRINT_SERVICE_BASE_URL,
		NEXT_PUBLIC_APP_MATOMO_BASE_URL: process.env.NEXT_PUBLIC_APP_MATOMO_BASE_URL,
		NEXT_PUBLIC_APP_MATOMO_ID: process.env.NEXT_PUBLIC_APP_MATOMO_ID,
		NEXT_PUBLIC_APP_SENTRY_DSN: process.env.NEXT_PUBLIC_APP_SENTRY_DSN,
		NEXT_PUBLIC_APP_SENTRY_ORG: process.env.NEXT_PUBLIC_APP_SENTRY_ORG,
		NEXT_PUBLIC_APP_SENTRY_PII: process.env.NEXT_PUBLIC_APP_SENTRY_PII,
		NEXT_PUBLIC_APP_SENTRY_PROJECT: process.env.NEXT_PUBLIC_APP_SENTRY_PROJECT,
		NEXT_PUBLIC_APP_SERVICE_ID: process.env.NEXT_PUBLIC_APP_SERVICE_ID,
		NEXT_PUBLIC_TYPESENSE_RESOURCE_COLLECTION_NAME:
			process.env.NEXT_PUBLIC_TYPESENSE_RESOURCE_COLLECTION_NAME,
		NEXT_PUBLIC_TYPESENSE_WEBSITE_COLLECTION_NAME:
			process.env.NEXT_PUBLIC_TYPESENSE_WEBSITE_COLLECTION_NAME,
		NEXT_PUBLIC_TYPESENSE_HOST: process.env.NEXT_PUBLIC_TYPESENSE_HOST,
		NEXT_PUBLIC_TYPESENSE_PORT: process.env.NEXT_PUBLIC_TYPESENSE_PORT,
		NEXT_PUBLIC_TYPESENSE_PROTOCOL: process.env.NEXT_PUBLIC_TYPESENSE_PROTOCOL,
		NEXT_PUBLIC_TYPESENSE_SEARCH_API_KEY: process.env.NEXT_PUBLIC_TYPESENSE_SEARCH_API_KEY,
		NEXT_RUNTIME: process.env.NEXT_RUNTIME,
		REVALIDATION_WEBHOOK_SECRET: process.env.REVALIDATION_WEBHOOK_SECRET,
		REVALIDATION_WEBHOOK_URL: process.env.REVALIDATION_WEBHOOK_URL,
		S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
		S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
		S3_HOST: process.env.S3_HOST,
		S3_PORT: process.env.S3_PORT,
		S3_PROTOCOL: process.env.S3_PROTOCOL,
		S3_SECRET_KEY: process.env.S3_SECRET_KEY,
		SEARCH_SYNC_API_SECRET: process.env.SEARCH_SYNC_API_SECRET,
		SSHOC_MARKETPLACE_API_BASE_URL: process.env.SSHOC_MARKETPLACE_API_BASE_URL,
		SSHOC_MARKETPLACE_BASE_URL: process.env.SSHOC_MARKETPLACE_BASE_URL,
		TYPESENSE_ADMIN_API_KEY: process.env.TYPESENSE_ADMIN_API_KEY,
		ZOTERO_API_BASE_URL: process.env.ZOTERO_API_BASE_URL,
		ZOTERO_API_KEY: process.env.ZOTERO_API_KEY,
		ZOTERO_GROUP_ID: process.env.ZOTERO_GROUP_ID,
	},
}).unwrap();
